### ISSUE TITLE
Template Filter UI

### ISSUE THREAD

**Issue by BrittanyIRL** [google/web-stories-wp#9507]
## Description
UI prep in storybook for filtering. Since our designs are a little out of date doing this in storybook and having discussion with design to iterate on anything that's weird will be proactive. 

Here's the designs in figma for the redesigned explore templates view in the existing design system: https://www.figma.com/file/Ha6kk9yXDN1rB80NzcDf2J/_Editor---Design-System-%22Style-Guide%22?node-id=467%3A13745 

![Screen Shot 2021-10-22 at 11.38.03 AM.png](https://images.zenhubusercontent.com/5e9dcd9a9ff5dfdaffcdf132/e639aaf8-85cf-44f7-be9f-2b9f20e0ba52)

These (i think) are all multi select inputs in these dropdowns, so when menus expand popups show [like this](https://www.figma.com/file/hUTw97921an0e3uU28JoDn/Dashboard?node-id=1575%3A39026) (only in the new styles) 
![Screen Shot 2021-10-22 at 11.40.45 AM.png](https://images.zenhubusercontent.com/5e9dcd9a9ff5dfdaffcdf132/1dbab95a-b1fd-4086-bc3a-c7ee61f24c5c) 

When 1 selection is made it'll show like this (only in the new styles):
![Screen Shot 2021-10-22 at 11.42.48 AM.png](https://images.zenhubusercontent.com/5e9dcd9a9ff5dfdaffcdf132/0f71359a-465a-4f84-bc67-9aaff57de0c0)

And when more than 1 selection is made it'll add a `+n` to the end of the content, there was a really old google drive demo of this that i'm remembering. 

I've asked design about these but I didn't think this was coming up so quickly - so there's a chance this is wrong and that's fine. I think we can iterate on the general idea with design and be fine. 

## Acceptance Criteria 
-  UI decided on for these templates and a demo of it working in the explore templates header of storybook.

**Comment by maxyinger** [comment]
did some research into this. some things I wanna cover in the design meeting:

1) I don't think we have any way of sorting by `popular` templates, might be nice to drop this toggle

2) The filters in `My Stories` are beneath the search instead of inbetween the title and the search. I think mirroring this for the templates could help fit on a 13" screen better as well as provide better visual continuity for a user as far as where filters/sorting are on the page

3) Did a little audit of template colors and right now we have 184 unique colors. I think this is too many for a user to parse through and we wouldn't be able to automate sorting them well (this is a hard problem in programming). I'm wondering if it makes more sense here to just have like 8 parent color options and we can filter based on if a template has a color close to that parent color. I'm curious if anyone has any color filter reference points on the web. I have a few I can share.

4) we currently have 164 unique tags as well. this may be fine to just use our datalist input that we're using for authors in this PR https://github.com/google/web-stories-wp/pull/9539
